#!/usr/bin/env bash
# deploy.sh — Build and deploy the entire Second Brain stack
#
# Usage:
#   ./deploy.sh              # Interactive setup + deploy
#   ./deploy.sh --defaults   # Deploy with defaults (no prompts)
#   ./deploy.sh down         # Tear down all services
#   ./deploy.sh status       # Show running services and ports
#   ./deploy.sh logs [svc]   # Tail logs (optionally for one service)
#   ./deploy.sh ingest       # Run one-shot note ingestion
#   ./deploy.sh embed        # Run one-shot embedding pipeline
#   ./deploy.sh cli <args>   # Run sb CLI inside the container

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

COMPOSE_FILE="docker-compose.prod.yml"
PROJECT_NAME="secondbrain"
ENV_FILE=".env.prod"

# ── Colors ────────────────────────────────────────────────
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
BOLD='\033[1m'
NC='\033[0m'

info()  { echo -e "${BLUE}[INFO]${NC} $*"; }
ok()    { echo -e "${GREEN}[OK]${NC} $*"; }
warn()  { echo -e "${YELLOW}[WARN]${NC} $*"; }
err()   { echo -e "${RED}[ERROR]${NC} $*" >&2; }

# Wrapper — pass env file only if it exists
compose() {
    local args=(-f "$COMPOSE_FILE" -p "$PROJECT_NAME")
    if [ -f "$ENV_FILE" ]; then
        args+=(--env-file "$ENV_FILE")
    fi
    docker compose "${args[@]}" "$@"
}

# ── Prerequisites ─────────────────────────────────────────
check_prereqs() {
    local missing=()
    command -v docker >/dev/null 2>&1 || missing+=("docker")
    docker compose version >/dev/null 2>&1 || missing+=("docker-compose-plugin")
    if [ ${#missing[@]} -gt 0 ]; then
        err "Missing required tools: ${missing[*]}"
        err "Install Docker (with compose plugin): https://docs.docker.com/get-docker/"
        exit 1
    fi
    ok "Prerequisites satisfied (docker + compose plugin)"
}

# ── Configure ─────────────────────────────────────────────
configure() {
    local defaults="${1:-false}"

    # Defaults
    local db_port="5432"
    local db_password="secondbrain"
    local ollama_port="11434"
    local mcp_port="8080"
    local embedding_preset="nomic"
    local ollama_model="nomic-embed-text"
    local notes_path="${HOME}/2_resources/notes"
    local log_level="info"

    if [ "$defaults" = "false" ]; then
        echo ""
        echo -e "${BOLD}${CYAN}── Second Brain Deploy Configuration ──${NC}"
        echo ""

        # Notes path
        read -rp "Notes directory [$notes_path]: " input
        notes_path="${input:-$notes_path}"

        if [ ! -d "$notes_path" ]; then
            warn "Directory '$notes_path' does not exist."
            read -rp "Create it? [Y/n]: " create
            if [[ "${create:-Y}" =~ ^[Yy] ]]; then
                mkdir -p "$notes_path"
                ok "Created $notes_path"
            fi
        fi

        # DB password
        read -rp "Database password [secondbrain]: " input
        db_password="${input:-$db_password}"

        # Ports
        read -rp "PostgreSQL port [$db_port]: " input
        db_port="${input:-$db_port}"

        read -rp "Ollama port [$ollama_port]: " input
        ollama_port="${input:-$ollama_port}"

        read -rp "MCP server port [$mcp_port]: " input
        mcp_port="${input:-$mcp_port}"

        # Embedding model (Ollama)
        echo ""
        echo "Ollama embedding models:"
        echo "  1) nomic-embed-text    (768d, 137MB — fast, good quality, default)"
        echo "  2) all-minilm          (384d,  46MB — fastest, smallest)"
        echo "  3) snowflake-arctic-embed (1024d, 670MB — high quality)"
        echo "  4) mxbai-embed-large   (1024d, 670MB — high quality)"
        echo "  5) qwen3-embedding     (1024d, 4.7GB — best quality, largest)"
        read -rp "Choose [1]: " choice
        case "${choice:-1}" in
            2) embedding_preset="all-minilm";   ollama_model="all-minilm" ;;
            3) embedding_preset="snowflake";     ollama_model="snowflake-arctic-embed" ;;
            4) embedding_preset="mxbai";         ollama_model="mxbai-embed-large" ;;
            5) embedding_preset="qwen3";         ollama_model="qwen3-embedding" ;;
            *) ;;  # keep nomic defaults
        esac

        # Log level
        read -rp "Log level (debug/info/warn/error) [$log_level]: " input
        log_level="${input:-$log_level}"
    fi

    # Resolve to absolute path
    notes_path="$(cd "$notes_path" 2>/dev/null && pwd || echo "$notes_path")"

    # Write .env.prod
    cat > "$ENV_FILE" <<EOF
# Second Brain — Production Environment
# Generated by deploy.sh on $(date -Iseconds)

# Database
POSTGRES_USER=secondbrain
POSTGRES_PASSWORD=${db_password}
POSTGRES_DB=secondbrain
DB_PORT=${db_port}

# Ollama
OLLAMA_PORT=${ollama_port}
OLLAMA_MODEL=${ollama_model}
EMBEDDING_PRESET=${embedding_preset}

# MCP Server
MCP_PORT=${mcp_port}

# Notes
NOTES_PATH=${notes_path}

# Logging
RUST_LOG=${log_level}
EOF

    ok "Configuration written to $ENV_FILE"
}

# ── Build & Deploy ────────────────────────────────────────
deploy() {
    info "Building application container..."
    compose build app

    info "Starting all services..."
    compose up -d

    # ── Wait for health ───────────────────────────────────
    info "Waiting for services to be healthy..."
    local timeout=180
    local elapsed=0
    while [ $elapsed -lt $timeout ]; do
        # Count containers that report "healthy" in their status
        local healthy
        healthy=$(docker ps --filter "name=secondbrain-" --format '{{.Status}}' | grep -c "(healthy)" || true)
        if [ "$healthy" -ge 2 ]; then
            break
        fi
        sleep 3
        elapsed=$((elapsed + 3))
        printf "\r  Waiting... %ds / %ds (${healthy}/2 healthy)" "$elapsed" "$timeout"
    done
    echo ""

    if [ $elapsed -ge $timeout ]; then
        warn "Timed out waiting for services. Check: ./deploy.sh logs"
        return 1
    fi
    ok "Database and Ollama are healthy."

    # ── Pull embedding model ──────────────────────────────
    # shellcheck disable=SC1090
    source "$ENV_FILE"
    local model="${OLLAMA_MODEL:-nomic-embed-text}"

    info "Ensuring Ollama model '${model}' is available..."
    if docker exec secondbrain-ollama ollama list 2>/dev/null | grep -q "$model"; then
        ok "Model '${model}' already pulled."
    else
        info "Pulling '${model}' (this may take a minute on first run)..."
        docker exec secondbrain-ollama ollama pull "$model"
        ok "Model '${model}' pulled."
    fi

    # ── Initial ingestion + embedding ─────────────────────
    info "Running initial note ingestion..."
    compose exec -T app sb ingest /data/notes 2>&1 || warn "Ingestion had warnings (may be first run)"

    info "Running initial embedding..."
    compose exec -T app sb embed 2>&1 || warn "Embedding had warnings (may be first run)"

    show_status
}

# ── Status ────────────────────────────────────────────────
show_status() {
    echo ""
    echo -e "${BOLD}${CYAN}═══════════════════════════════════════════════════${NC}"
    echo -e "${BOLD}${CYAN}  Second Brain — Deployment Status${NC}"
    echo -e "${BOLD}${CYAN}═══════════════════════════════════════════════════${NC}"
    echo ""

    local db_port="5432"
    local ollama_port="11434"
    local mcp_port="8080"
    if [ -f "$ENV_FILE" ]; then
        # shellcheck disable=SC1090
        source "$ENV_FILE"
        db_port="${DB_PORT:-5432}"
        ollama_port="${OLLAMA_PORT:-11434}"
        mcp_port="${MCP_PORT:-8080}"
    fi

    echo -e "${BOLD}Services:${NC}"
    docker ps --filter "name=secondbrain-" --format "table {{.Names}}\t{{.Status}}\t{{.Ports}}" 2>/dev/null || \
        compose ps

    echo ""
    echo -e "${BOLD}Exposed Ports:${NC}"
    echo -e "  ${GREEN}MCP Server${NC} : localhost:${mcp_port}/mcp"
    echo -e "  ${GREEN}PostgreSQL${NC} : localhost:${db_port}"
    echo -e "  ${GREEN}Ollama${NC}     : localhost:${ollama_port}"
    echo ""
    echo -e "${BOLD}Connection:${NC}"
    echo -e "  MCP URL  : http://localhost:${mcp_port}/mcp"
    echo -e "  DB URL   : postgresql://secondbrain:***@localhost:${db_port}/secondbrain"
    echo -e "  Ollama   : http://localhost:${ollama_port}"
    echo ""
    echo -e "${BOLD}Commands:${NC}"
    echo -e "  ${CYAN}./deploy.sh status${NC}              — Show this status"
    echo -e "  ${CYAN}./deploy.sh logs${NC}                — Tail all logs"
    echo -e "  ${CYAN}./deploy.sh logs ollama${NC}         — Tail one service"
    echo -e "  ${CYAN}./deploy.sh ingest${NC}              — Re-ingest notes"
    echo -e "  ${CYAN}./deploy.sh embed${NC}               — Re-run embeddings"
    echo -e "  ${CYAN}./deploy.sh cli search \"query\"${NC}  — Search via CLI"
    echo -e "  ${CYAN}./deploy.sh down${NC}                — Stop all services"
    echo ""
}

# ── Tear down ─────────────────────────────────────────────
teardown() {
    info "Stopping all services..."
    compose down
    ok "All services stopped. Data volumes preserved."
    echo "  To remove volumes too: docker compose -f $COMPOSE_FILE -p $PROJECT_NAME down -v"
}

# ── Main ──────────────────────────────────────────────────
main() {
    echo -e "${BOLD}${CYAN}"
    echo "  ╔═══════════════════════════════════╗"
    echo "  ║       Second Brain Deploy         ║"
    echo "  ║   CLI + MCP Server + Database     ║"
    echo "  ╚═══════════════════════════════════╝"
    echo -e "${NC}"

    case "${1:-}" in
        down|stop)
            teardown
            ;;
        status)
            show_status
            ;;
        logs)
            shift
            compose logs -f "$@"
            ;;
        ingest)
            info "Running note ingestion..."
            compose exec -T app sb ingest /data/notes
            ok "Ingestion complete."
            ;;
        embed)
            info "Running embedding pipeline..."
            compose exec -T app sb embed
            ok "Embedding complete."
            ;;
        cli)
            shift
            compose exec -T app sb "$@"
            ;;
        --defaults)
            check_prereqs
            configure true
            deploy
            ;;
        ""|deploy)
            check_prereqs
            configure false
            deploy
            ;;
        *)
            echo "Usage: $0 [deploy|down|status|logs [svc]|ingest|embed|cli <args>|--defaults]"
            exit 1
            ;;
    esac
}

main "$@"
